version: 2
project_name: vacuum
before:
  hooks:
    - ./scripts/build-ui-assets.sh
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    tags:
      - html_report_ui
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
  - id: darwin
    env:
      - CGO_ENABLED=0
    tags:
      - html_report_ui
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - darwin
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 20m

homebrew_casks:
  - repository:
      owner: daveshanley
      name: homebrew-vacuum

    commit_author:
      name: goreleaserbot
      email: goreleaser@quobix.com

    homepage: "https://quobix.com/vacuum"
    description: "The worlds fastest and most scalable OpenAPI linter"

snapshot:
  version_template: "{{ .Tag }}"
