project_name: vacuum
# before:
#   hooks:
#     # Removed go mod tidy to prevent dirty state during build
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - repository:
      owner: daveshanley
      name: homebrew-vacuum

    commit_author:
      name: goreleaserbot
      email: goreleaser@quobix.com

    homepage: "https://quobix.com/vacuum"
    description: "The worlds fastest and most scalable OpenAPI linter"

    install: |
      bin.install "vacuum"

snapshot:
  name_template: "{{ .Tag }}"