//go:build html_report_ui

package html_report

import _ "embed"

// UI bundles are generated by scripts/build-ui-assets.sh before official builds.
//
//go:embed ui/build/static/js/vacuumReport.js
var bundledJS string

//go:embed ui/build/static/js/hydrate.js
var hydrateJS string

const htmlReportUIEnabled = true
