import 'terminal.css';
import '../components/charts/category-piechart-component.init';
import '../components/rule-category-navigation/rule-category-navigation.init';
import '../components/rule-category-navigation/rule-category-button.init';
import '../components/html-report/html-report-component.init';
import '../components/html-report/category-report-component.init';
import '../components/html-report/category-rule-result-component.init';
import '../components/html-report/category-rule-component.init';
import '../components/html-report/category-rules-component.init';
